name: Dotnet Test and Publish Results

on:
  workflow_call:
    inputs:
      project_path:
        description: 'The project path is where the solution file is located'
        required: true
        type: string
      dotnet-version:
        description: "The Dotnet version to use"
        required: true
        type: string
    secrets:
      nuget_username:
        description: Nuget username
        required: true
      nuget_pat:
        description: Nuget PAT token
        required: true

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test-and-publish-results:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        
    - name: Configure NuGet Package Source
      run: dotnet nuget add source https://nuget.pkg.github.com/cloudfactorydk/index.json -n cf-github -u ${{ secrets.nuget_username }} -p ${{ secrets.nuget_pat }} --store-password-in-clear-text
        
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project_path }}
    
    - name: Build Solution
      run: dotnet build ${{ inputs.project_path }} -c Release
    
    - name: Test
      run: dotnet test ${{ inputs.project_path }} -c Release --verbosity normal --logger "trx;logfilename=testResults.trx"
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/TestResults/*.trx