name: Create and Publish Docker Container

on:
  workflow_call:
    inputs:
      project_path:
        description: 'The project path is where the Solution file is located'
        required: true
        type: string
      dockerfile_path:
        description: 'Path to the Dockerfile'
        required: true
        type: string
      docker_image_name:
        description: 'Docker image name'
        required: true
        type: string
      artifact_name:
        description: 'Name of the artifact that should be used'
        required: false
        default: ''
        type: string
      artifact_path:
        description: 'Path for artifact'
        required: false
        default: './'
        type: string
      github_runner:
        description: 'Which runner should be used in this workflow'
        required: false
        type: string
        default: 'ubuntu-latest'
    secrets:
      gh_token:
        description: Github PAT token to perform login to Github Container Registry
        required: true
      nuget_username:
        description: Nuget username
        required: true
      nuget_pat:
        description: Nuget PAT token
        required: true

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: write


jobs:
  create-and-publish-docker-container:
    name: ${{inputs.docker_image_name }} - Create & Publish
    runs-on: ${{ inputs.github_runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        if: ${{ inputs.artifact_name != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}

      - name: Short git SHA
        id: git_sha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> $GITHUB_ENV
          echo $calculatedSha
          
      - name: Normalize Git Branch Name
        id: normalize_branch
        run: |
          branch_name=${{ github.ref_name }}
          normalized_branch=$(echo "$branch_name" | sed -E 's/[^[:alnum:]-]+/-/g')
          echo "normalized_branch=$normalized_branch" >> $GITHUB_ENV
          echo "Normalized branch name: $normalized_branch"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image_name }}
          
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.normalized_branch }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and Push Docker Images
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.project_path }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          file: ${{ inputs.dockerfile_path }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PAT_USERNAME=${{ secrets.nuget_username }}
            PAT=${{ secrets.nuget_pat }}
            GIT_HASH=${{ env.short_sha }}
            GIT_BRANCH=${{ env.normalized_branch }}
